# Generated by Django 5.0.6 on 2024-05-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip_code',
            new_name='pin_code',
        ),
    ]
